package com.mycompany.asiakastilausjarjestelma;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Tuoterekisterihallinta extends javax.swing.JFrame {

    private Tilaustenhallinta paa;

    public Tuoterekisterihallinta() {
        initComponents();
        NaytaTuotteet();
        jPanel1.setVisible(false);
    }

    public Tuoterekisterihallinta(Object lisaa) {
        initComponents();
        NaytaTuotteet();
        paa = (Tilaustenhallinta) lisaa;
        jPanel1.setVisible(true);
    }

    public void sulje() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    class Tuote {

        private int tuotenumero;
        private String tuotenimi;
        private String selite;
        private double ahinta;

        public Tuote(int tuotenumero, String tuotenimi, String selite, double ahinta) {
            this.tuotenumero = tuotenumero;
            this.tuotenimi = tuotenimi;
            this.selite = selite;
            this.ahinta = ahinta;
        }

        public int HaeTuotenumero() {
            return this.tuotenumero;
        }

        public String HaeTuotenimi() {
            return this.tuotenimi;
        }

        public String HaeSelite() {
            return this.selite;
        }

        public double HaeAhinta() {
            return this.ahinta;
        }
    }

    public Connection luoYhteys() {
        Connection cn = null;

        try {
            cn = DriverManager.getConnection("jdbc:mariadb://" + "ec2-13-49-231-56.eu-north-1.compute.amazonaws.com" + ":3306/ASIAKASTILAUS", "kehittaja", "Koira123!");
            return cn;
        } catch (SQLException e) {
            System.out.println("Yhteyden luominen epäonnistui!:\n" + e.getMessage());
            e.printStackTrace();
            return null;
        }
    }

    public ArrayList<Tuote> HaeTuoteTaulukko() {
        ArrayList<Tuote> Tuotetaulukko = new ArrayList<Tuote>();

        Connection yhteys = luoYhteys();

        String query = "Select tuotenumero, tuotenimi, selite, ahinta FROM TUOTE";
        Statement st;
        ResultSet rs;

        try {
            st = yhteys.createStatement();
            rs = st.executeQuery(query);

            Tuote a;

            while (rs.next()) {
                a = new Tuote(rs.getInt("Tuotenumero"), rs.getString("Tuotenimi"),
                        rs.getString("Selite"), rs.getDouble("Ahinta"));
                Tuotetaulukko.add(a);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return Tuotetaulukko;
    }

    public void NaytaTuotteet() {
        ArrayList<Tuote> list = HaeTuoteTaulukko();
        DefaultTableModel model = (DefaultTableModel) jtblTuote.getModel();

        model.setColumnIdentifiers(new Object[]{"Tuotenumero", "Tuotenimi", "Selite",
            "Ahinta"});
        Object[] row = new Object[4];

        for (int i = jtblTuote.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).HaeTuotenumero();
            row[1] = list.get(i).HaeTuotenimi();
            row[2] = list.get(i).HaeSelite();
            row[3] = list.get(i).HaeAhinta();

            model.addRow(row);
        }
    }

    public void suoritaSQLKysely(String query, String message) {
        Connection yhteys = luoYhteys();
        Statement st;
        try {
            st = yhteys.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                DefaultTableModel model = (DefaultTableModel) jtblTuote.getModel();
                model.setRowCount(0);
                NaytaTuotteet();

                JOptionPane.showMessageDialog(null, "Data " + message + " onnistuneesti");
            } else {
                JOptionPane.showMessageDialog(null, "Data ei " + message);
            }
            yhteys.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTuote = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtTuotenumero = new javax.swing.JTextField();
        jtxtTuotenimi = new javax.swing.JTextField();
        jtxtSelite = new javax.swing.JTextField();
        jtxtAhinta = new javax.swing.JTextField();
        jbtnUusi = new javax.swing.JButton();
        jbtnPäivitä = new javax.swing.JButton();
        jbtnPoista = new javax.swing.JButton();
        jbtnTestaa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtxtMaara = new javax.swing.JTextField();
        jbtnLisaaTilaukseen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtblTuote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblTuote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTuoteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblTuote);

        jLabel1.setText("Tuoterekisteri");

        jLabel2.setText("Tuotenumero:");

        jLabel3.setText("Tuotenimi:");

        jLabel4.setText("Selite:");

        jLabel5.setText("Ahinta:");

        jtxtAhinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAhintaActionPerformed(evt);
            }
        });

        jbtnUusi.setText("Uusi");
        jbtnUusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUusiActionPerformed(evt);
            }
        });

        jbtnPäivitä.setText("Päivitä");
        jbtnPäivitä.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPäivitäActionPerformed(evt);
            }
        });

        jbtnPoista.setText("Poista");
        jbtnPoista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPoistaActionPerformed(evt);
            }
        });

        jbtnTestaa.setText("Testaa tietokantayhteys Amazon MarianDB-palvelimeen");
        jbtnTestaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTestaaActionPerformed(evt);
            }
        });

        jLabel6.setText("Määrä:");

        jbtnLisaaTilaukseen.setText("Lisää tilaukseen");
        jbtnLisaaTilaukseen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLisaaTilaukseenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnLisaaTilaukseen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnLisaaTilaukseen)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnUusi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnPäivitä)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnPoista, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnTestaa))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jtxtSelite, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                                    .addComponent(jtxtTuotenumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtxtTuotenimi)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtxtAhinta, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtTuotenumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTuotenimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtSelite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtAhinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnPoista)
                            .addComponent(jbtnPäivitä)
                            .addComponent(jbtnUusi)
                            .addComponent(jbtnTestaa)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtAhintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAhintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAhintaActionPerformed

    private boolean Tarkistaa() {
        if (jtxtTuotenumero.getText().isBlank() || jtxtTuotenimi.getText().isBlank()
                || jtxtSelite.getText().isBlank() || jtxtAhinta.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Kentät eivät täytyy olla tyhjiä.", "HUOM!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void jbtnUusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUusiActionPerformed
        try {
            Integer.parseInt(jtxtTuotenumero.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tuotenumero täytyy olla lukuna.", "HUOM!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Tarkistaa() == false) {
            return;
        }

        int tulos = JOptionPane.showConfirmDialog(null, "Haluaanko suorittaa tuotteen lisäys?", "Varmistuskysymys", JOptionPane.YES_NO_OPTION);

        if (tulos == JOptionPane.YES_OPTION) {
            String query = "INSERT INTO `TUOTE`(`TUOTENIMI`, `SELITE`, `AHINTA`)";
            query = query + " VALUES('" + jtxtTuotenimi.getText() + "','"
                    + jtxtSelite.getText() + "', '" + jtxtAhinta.getText() + "')";
            suoritaSQLKysely(query, "lisätty");
        }
    }//GEN-LAST:event_jbtnUusiActionPerformed

    private void jbtnPäivitäActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPäivitäActionPerformed
        if (Tarkistaa() == false) {
            return;
        }

        int tulos = JOptionPane.showConfirmDialog(null, "Haluaanko suorittaa tuotteen päivitys?", "Varmistuskysymys", JOptionPane.YES_NO_OPTION);

        if (tulos == JOptionPane.YES_OPTION) {
            String query = "UPDATE TUOTE SET TUOTENIMI='" + jtxtTuotenimi.getText() + "', "
                    + "SELITE='" + jtxtSelite.getText() + "', AHINTA='" + jtxtAhinta.getText()
                    + "' WHERE TUOTENUMERO = " + jtxtTuotenumero.getText();
            JOptionPane.showMessageDialog(null, query);
            suoritaSQLKysely(query, "Päivitetty");
        }
    }//GEN-LAST:event_jbtnPäivitäActionPerformed

    private void jbtnPoistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPoistaActionPerformed
        int tulos = JOptionPane.showConfirmDialog(null, "Haluaanko suorittaa tuotteen poisto?", "Varmistuskysymys", JOptionPane.YES_NO_OPTION);

        if (tulos == JOptionPane.YES_OPTION) {
            String query = "DELETE FROM TUOTE WHERE TUOTENUMERO=" + jtxtTuotenumero.getText();
            suoritaSQLKysely(query, "Poistettu");
        }
    }//GEN-LAST:event_jbtnPoistaActionPerformed

    private void jtblTuoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTuoteMouseClicked
        int i = jtblTuote.getSelectedRow();
        TableModel model = jtblTuote.getModel();
        jtxtTuotenumero.setText(model.getValueAt(i, 0).toString());
        jtxtTuotenimi.setText(model.getValueAt(i, 1).toString());
        jtxtSelite.setText(model.getValueAt(i, 2).toString());
        jtxtAhinta.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jtblTuoteMouseClicked

    private void jbtnTestaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTestaaActionPerformed
        try {
            Class.forName("org.mariadb.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Missä on MariaDB JDBC ajuri? Oletko ladannut mariadb connectorin osoitteesta: https://mariadb.com/downloads/#connectors ja lisännyt sen Netbeansissä Asiakasrekisteri-Libraries-Add JAR/Folder kohdassa? ");
            e.printStackTrace();
            return;
        }

        System.out.println("Mariadb JDBC Driver rekisteröity!");
        Connection connection = null;

        try {
            connection = DriverManager.getConnection("jdbc:mariadb://" + "ec2-13-49-231-56.eu-north-1.compute.amazonaws.com" + ":3306/ASIAKASTILAUS", "kehittaja", "Koira123!");
        } catch (SQLException e) {
            System.out.println("Yhteyden luominen epäonnistui!:\n" + e.getMessage());
        }

        if (connection != null) {
            System.out.println("Hienoa ja onnittelut! Sait luotua yhteyden tietokantaasi. Voit aloittaa käyttöliittymän koodaamisen!");
        } else {
            System.out.println("Pahus, tarkista vielä, että kaikki tarvittava on tehty ja virheitä ei ole!");
        }
    }//GEN-LAST:event_jbtnTestaaActionPerformed

    private void jbtnLisaaTilaukseenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLisaaTilaukseenActionPerformed
        if (jtxtMaara.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Määrä ei täytyy olla tyhjä.", "HUOM!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int tuotenumero = Integer.valueOf(jtxtTuotenumero.getText());
        double ahinta = Double.valueOf(jtxtAhinta.getText());
        int maara = Integer.valueOf(jtxtMaara.getText());

        paa.LisaaTuote(tuotenumero, maara, ahinta);

        sulje();
    }//GEN-LAST:event_jbtnLisaaTilaukseenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tuoterekisterihallinta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tuoterekisterihallinta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tuoterekisterihallinta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tuoterekisterihallinta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tuoterekisterihallinta("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnLisaaTilaukseen;
    private javax.swing.JButton jbtnPoista;
    private javax.swing.JButton jbtnPäivitä;
    private javax.swing.JButton jbtnTestaa;
    private javax.swing.JButton jbtnUusi;
    private javax.swing.JTable jtblTuote;
    private javax.swing.JTextField jtxtAhinta;
    private javax.swing.JTextField jtxtMaara;
    private javax.swing.JTextField jtxtSelite;
    private javax.swing.JTextField jtxtTuotenimi;
    private javax.swing.JTextField jtxtTuotenumero;
    // End of variables declaration//GEN-END:variables
}
